spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
    open-in-view: true
    defer-datasource-initialization: true
    show_sql: true

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:b27e6460-479f-4b15-a2a5-4ef8601536e1
    username: dividend
    password:


scheduler:
  scrap:
    yahoo: 0 0 0 * * *